export const defaultConfig = {
  // Alertas básicas del sistema
  exito: {
    type: 'success',
    icon: 'fa-solid fa-circle-check',
    title: 'Éxito',
    message: 'Operación completada con éxito',
    duration: 5000,
  },
  contraseñaCambiada: {
    type: 'success',
    icon: 'fa-solid fa-circle-check',
    title: 'Éxito',
    message: 'Contrasena cambiada con éxito',
    duration: 5000,
  },
  contraseñaIncorrecta: {
    type: 'error',
    icon: 'fa-solid fa-key',
    title: 'Contraseña Invalida',
    message: 'La contraseña ingresada debe tener 8 digitos',
    duration: 5000,
  },
  codigoVerificado: {
    type: 'info',
    icon: 'fa-solid fa-circle-check',
    title: 'Codigo Verificado',
    message: 'El código ha sido verificado',
    duration: 5000,
  },
  codigoIncorrecto: {
    type: 'error',
    icon: 'fa-solid fa-key',
    title: 'Codigo Incorrecto',
    message: 'El código ingresado es incorrecto',
    duration: 5000,
  },
  error: {
    type: 'error',
    icon: 'fa-solid fa-circle-exclamation',
    title: 'Error',
    message: 'Ha ocurrido un error',
    duration: 5000,
  },
  advertencia: {
    type: 'warning',
    icon: 'fa-solid fa-triangle-exclamation',
    title: 'Advertencia',
    message: 'Por favor, tenga cuidado',
    duration: 5000,
  },
  informacion: {
    type: 'info',
    icon: 'fa-solid fa-circle-info',
    title: 'Información',
    message: 'Aquí hay información importante',
    duration: 5000,
  },

  // Alertas de registro de usuarios
  inicioSesionExitoso: {
    type: 'success',
    icon: 'fa-solid fa-right-to-bracket',
    title: 'Inicio de Sesión',
    message: 'Has iniciado sesión correctamente',
    duration: 5000,
  },
  contrasenaIncorrecta: {
    type: 'error',
    icon: 'fa-solid fa-key',
    title: 'Contraseña Incorrecta',
    message: 'La contraseña ingresada no es válida',
    duration: 5000,
  },
  usuarioNoEncontrado: {
    type: 'error',
    icon: 'fa-solid fa-user-slash',
    title: 'Usuario No Encontrado',
    message: 'El usuario no está registrado',
    duration: 5000,
  },
  camposVacios: {
    type: 'warning',
    icon: 'fa-solid fa-exclamation-circle',
    title: 'Campos Vacíos',
    message: 'Por favor, completa todos los campos',
    duration: 5000,
  },
  cuentaBloqueada: {
    type: 'error',
    icon: 'fa-solid fa-lock',
    title: 'Cuenta Bloqueada',
    message: 'Tu cuenta ha sido bloqueada temporalmente',
    duration: 5000,
  },
  errorServidor: {
    type: 'error',
    icon: 'fa-solid fa-server',
    title: 'Error del Servidor',
    message: 'No se pudo conectar con el servidor',
    duration: 5000,
  },
  sesionExpirada: {
    type: 'info',
    icon: 'fa-solid fa-clock',
    title: 'Sesión Expirada',
    message: 'Tu sesión ha expirado. Por favor, vuelve a iniciar sesión',
    duration: 5000,
  },
  inicioSesionCancelado: {
    type: 'warning',
    icon: 'fa-solid fa-ban',
    title: 'Inicio Cancelado',
    message: 'El inicio de sesión fue cancelado por el usuario',
    duration: 5000,
  },

  // Alertas de registro de pacientes
  registroPaciente: {
    type: 'success',
    icon: 'fa-solid fa-user-plus',
    title: 'Registro de Paciente',
    message: 'Paciente registrado correctamente',
    duration: 5000,
  },
  actualizacionPaciente: {
    type: 'success',
    icon: 'fa-solid fa-user-pen',
    title: 'Actualización de Paciente',
    message: 'Datos del paciente actualizados correctamente',
    duration: 5000,
  },
  eliminacionPaciente: {
    type: 'success',
    icon: 'fa-solid fa-user-minus',
    title: 'Eliminación de Paciente',
    message: 'Paciente eliminado correctamente',
    duration: 5000,
  },
  pacienteNoEncontrado: {
    type: 'error',
    icon: 'fa-solid fa-user-slash',
    title: 'Paciente no Encontrado',
    message: 'No se encontró al paciente solicitado',
    duration: 5000,
  },
  busquedaPaciente: {
    type: 'info',
    icon: 'fa-solid fa-magnifying-glass',
    title: 'Búsqueda de Paciente',
    message: 'Buscando información del paciente',
    duration: 3000,
  },
  importarPacientes: {
    type: 'info',
    icon: 'fa-solid fa-file-import',
    title: 'Importación de Pacientes',
    message: 'Importando lista de pacientes',
    duration: 5000,
  },
  exportarPacientes: {
    type: 'success',
    icon: 'fa-solid fa-file-export',
    title: 'Exportación de Pacientes',
    message: 'Lista de pacientes exportada correctamente',
    duration: 5000,
  },
  archivarPaciente: {
    type: 'info',
    icon: 'fa-solid fa-box-archive',
    title: 'Archivar Paciente',
    message: 'Paciente archivado correctamente',
    duration: 4000,
  },
  restaurarPaciente: {
    type: 'success',
    icon: 'fa-solid fa-trash-arrow-up',
    title: 'Restaurar Paciente',
    message: 'Paciente restaurado correctamente',
    duration: 4000,
  },

  // Alertas de citas
  crearCita: {
    type: 'success',
    icon: 'fa-solid fa-calendar-plus',
    title: 'Cita',
    message: 'Cita agendada correctamente',
    duration: 5000,
  },
  actualizarCita: {
    type: 'success',
    icon: 'fa-solid fa-calendar-day',
    title: 'Actualización de Cita',
    message: 'Cita modificada correctamente',
    duration: 5000,
  },
  cancelarCita: {
    type: 'warning',
    icon: 'fa-solid fa-calendar-xmark',
    title: 'Cancelación de Cita',
    message: 'Cita cancelada',
    duration: 5000,
  },
  recordatorioCita: {
    type: 'info',
    icon: 'fa-solid fa-bell',
    title: 'Recordatorio',
    message: 'Recordatorio de cita próxima',
    duration: 7000,
  },
  reagendarCita: {
    type: 'info',
    icon: 'fa-solid fa-calendar-days',
    title: 'Reagendar Cita',
    message: 'Cita reagendada correctamente',
    duration: 5000,
  },
  confirmacionCita: {
    type: 'success',
    icon: 'fa-solid fa-calendar-check',
    title: 'Confirmación de Cita',
    message: 'Cita confirmada por el paciente',
    duration: 4000,
  },
  citaVencida: {
    type: 'warning',
    icon: 'fa-solid fa-hourglass-end',
    title: 'Cita Vencida',
    message: 'La cita ha expirado sin asistencia',
    duration: 5000,
  },
  citaIniciada: {
    type: 'info',
    icon: 'fa-solid fa-door-open',
    title: 'Inicio de Consulta',
    message: 'La consulta médica ha iniciado',
    duration: 4000,
  },
  citaFinalizada: {
    type: 'success',
    icon: 'fa-solid fa-clipboard-check',
    title: 'Fin de Consulta',
    message: 'La consulta médica ha finalizado',
    duration: 4000,
  },
  pacienteEnEspera: {
    type: 'info',
    icon: 'fa-solid fa-person-circle-question',
    title: 'Paciente en Espera',
    message: 'El paciente está en sala de espera',
    duration: 4000,
  },

  // Alertas de historias clínicas
  crearHistoria: {
    type: 'success',
    icon: 'fa-solid fa-notes-medical',
    title: 'Historia Clínica',
    message: 'Historia clínica creada correctamente',
    duration: 5000,
  },
  actualizarHistoria: {
    type: 'success',
    icon: 'fa-solid fa-file-medical',
    title: 'Actualización de Historia',
    message: 'Historia clínica actualizada correctamente',
    duration: 5000,
  },
  accesoHistoria: {
    type: 'info',
    icon: 'fa-solid fa-file-circle-check',
    title: 'Acceso a Historia Clínica',
    message: 'Accediendo a la historia clínica del paciente',
    duration: 4000,
  },
  imprimirHistoria: {
    type: 'info',
    icon: 'fa-solid fa-print',
    title: 'Imprimir Historia',
    message: 'Imprimiendo historia clínica',
    duration: 4000,
  },
  adjuntarDocumento: {
    type: 'success',
    icon: 'fa-solid fa-paperclip',
    title: 'Documento Adjunto',
    message: 'Documento adjuntado correctamente',
    duration: 4000,
  },
  eliminarDocumento: {
    type: 'warning',
    icon: 'fa-solid fa-file-circle-xmark',
    title: 'Eliminar Documento',
    message: 'Documento eliminado correctamente',
    duration: 4000,
  },
  compartirHistoria: {
    type: 'info',
    icon: 'fa-solid fa-share-nodes',
    title: 'Compartir Historia',
    message: 'Historia clínica compartida correctamente',
    duration: 5000,
  },
  firmarDocumento: {
    type: 'success',
    icon: 'fa-solid fa-signature',
    title: 'Firmar Documento',
    message: 'Documento firmado correctamente',
    duration: 4000,
  },

  // Alertas de facturación
  crearFactura: {
    type: 'success',
    icon: 'fa-solid fa-file-invoice-dollar',
    title: 'Facturación',
    message: 'Factura generada correctamente',
    duration: 5000,
  },
  pagoRecibido: {
    type: 'success',
    icon: 'fa-solid fa-hand-holding-dollar',
    title: 'Pago Recibido',
    message: 'Pago registrado correctamente',
    duration: 5000,
  },
  pagoPendiente: {
    type: 'warning',
    icon: 'fa-solid fa-money-check',
    title: 'Pago Pendiente',
    message: 'El paciente tiene un pago pendiente',
    duration: 6000,
  },
  facturaVencida: {
    type: 'error',
    icon: 'fa-solid fa-receipt',
    title: 'Factura Vencida',
    message: 'La factura ha vencido sin pago',
    duration: 6000,
  },
  recordatorioPago: {
    type: 'warning',
    icon: 'fa-solid fa-bell-concierge',
    title: 'Recordatorio de Pago',
    message: 'Recordatorio de pago enviado al paciente',
    duration: 5000,
  },
  descuentoAplicado: {
    type: 'success',
    icon: 'fa-solid fa-percent',
    title: 'Descuento Aplicado',
    message: 'Se ha aplicado un descuento a la factura',
    duration: 4000,
  },
  imprimirFactura: {
    type: 'info',
    icon: 'fa-solid fa-print',
    title: 'Imprimir Factura',
    message: 'Imprimiendo factura',
    duration: 3000,
  },
  enviarFactura: {
    type: 'success',
    icon: 'fa-solid fa-paper-plane',
    title: 'Enviar Factura',
    message: 'Factura enviada al correo del paciente',
    duration: 4000,
  },
  anularFactura: {
    type: 'warning',
    icon: 'fa-solid fa-ban',
    title: 'Anular Factura',
    message: 'Factura anulada correctamente',
    duration: 5000,
  },
  reembolso: {
    type: 'info',
    icon: 'fa-solid fa-money-bill-transfer',
    title: 'Reembolso',
    message: 'Reembolso procesado correctamente',
    duration: 5000,
  },

  // Alertas de validación de datos
  errorValidacion: {
    type: 'error',
    icon: 'fa-solid fa-circle-exclamation',
    title: 'Error de Validación',
    message: 'Por favor, verifique los datos ingresados',
    duration: 6000,
  },
  registroDuplicado: {
    type: 'warning',
    icon: 'fa-solid fa-copy',
    title: 'Registro Duplicado',
    message: 'Ya existe un registro con estos datos',
    duration: 5000,
  },
  camposRequeridos: {
    type: 'warning',
    icon: 'fa-solid fa-asterisk',
    title: 'Campos Obligatorios',
    message: 'Complete todos los campos obligatorios',
    duration: 6000,
  },
  formatoInvalido: {
    type: 'error',
    icon: 'fa-solid fa-circle-xmark',
    title: 'Formato Inválido',
    message: 'El formato de los datos es incorrecto',
    duration: 5000,
  },
  datoGuardado: {
    type: 'success',
    icon: 'fa-solid fa-floppy-disk',
    title: 'Actualizado',
    message: 'El nombrer de la empresa se actualizo',
    duration: 4000,
  },

  // Alertas de seguridad y usuario
  sesionExpirada: {
    type: 'warning',
    icon: 'fa-solid fa-right-from-bracket',
    title: 'Sesión Expirada',
    message: 'Su sesión ha expirado, inicie sesión nuevamente',
    duration: 7000,
  },
  noAutorizado: {
    type: 'error',
    icon: 'fa-solid fa-ban',
    title: 'No Autorizado',
    message: 'No tiene permisos para realizar esta acción',
    duration: 6000,
  },
  inicioSesion: {
    type: 'success',
    icon: 'fa-solid fa-right-to-bracket',
    title: 'Inicio de Sesión',
    message: 'Ha iniciado sesión correctamente',
    duration: 4000,
  },
  cierreSesion: {
    type: 'info',
    icon: 'fa-solid fa-arrow-right-from-bracket',
    title: 'Cierre de Sesión',
    message: 'Ha cerrado sesión correctamente',
    duration: 4000,
  },
  cambioContrasena: {
    type: 'success',
    icon: 'fa-solid fa-key',
    title: 'Cambio de Contraseña',
    message: 'Su contraseña ha sido actualizada',
    duration: 5000,
  },
  intentoFallido: {
    type: 'error',
    icon: 'fa-solid fa-user-lock',
    title: 'Intento Fallido',
    message: 'Credenciales incorrectas',
    duration: 5000,
  },
  bloqueoUsuario: {
    type: 'error',
    icon: 'fa-solid fa-user-slash',
    title: 'Usuario Bloqueado',
    message: 'Su cuenta ha sido bloqueada temporalmente',
    duration: 7000,
  },
  verificacionDosPasos: {
    type: 'info',
    icon: 'fa-solid fa-shield-halved',
    title: 'Verificación',
    message: 'Código de verificación enviado',
    duration: 5000,
  },

  // Alertas de exámenes y laboratorio
  resultadoLaboratorio: {
    type: 'info',
    icon: 'fa-solid fa-flask',
    title: 'Resultados de Laboratorio',
    message: 'Resultados de laboratorio disponibles',
    duration: 6000,
  },
  recetaMedica: {
    type: 'success',
    icon: 'fa-solid fa-prescription',
    title: 'Receta Médica',
    message: 'Receta médica generada correctamente',
    duration: 5000,
  },
  ordenExamen: {
    type: 'info',
    icon: 'fa-solid fa-microscope',
    title: 'Orden de Examen',
    message: 'Orden de examen generada correctamente',
    duration: 5000,
  },
  enviarResultados: {
    type: 'success',
    icon: 'fa-solid fa-envelope-circle-check',
    title: 'Enviar Resultados',
    message: 'Resultados enviados al paciente',
    duration: 5000,
  },
  recordatorioMedicacion: {
    type: 'info',
    icon: 'fa-solid fa-pills',
    title: 'Recordatorio de Medicación',
    message: 'Recordatorio de medicación enviado',
    duration: 5000,
  },
  renovarReceta: {
    type: 'success',
    icon: 'fa-solid fa-prescription-bottle-medical',
    title: 'Renovar Receta',
    message: 'Receta médica renovada correctamente',
    duration: 5000,
  },

  // Alertas de personal médico
  nuevoTerapeuta: {
    type: 'success',
    icon: 'fa-solid fa-user-doctor',
    title: 'Nuevo Terapeuta',
    message: 'Terapeuta registrado correctamente',
    duration: 5000,
  },
  actualizarTerapeuta: {
    type: 'success',
    icon: 'fa-solid fa-id-card-clip',
    title: 'Datos Actualizados',
    message: 'Información del terapeuta actualizada',
    duration: 5000,
  },
  asignarTerapeuta: {
    type: 'info',
    icon: 'fa-solid fa-user-plus',
    title: 'Asignar Terapeuta',
    message: 'Terapeuta asignado al paciente',
    duration: 4000,
  },
  cambioProgramacion: {
    type: 'info',
    icon: 'fa-solid fa-calendar-range',
    title: 'Cambio de Programación',
    message: 'Horario del terapeuta actualizado',
    duration: 5000,
  },

  // Alertas de configuración del sistema
  configuracionGuardada: {
    type: 'success',
    icon: 'fa-solid fa-gear',
    title: 'Configuración',
    message: 'Configuración guardada correctamente',
    duration: 4000,
  },
  respaldoCreado: {
    type: 'success',
    icon: 'fa-solid fa-database',
    title: 'Respaldo',
    message: 'Respaldo de datos creado correctamente',
    duration: 5000,
  },
  restaurarSistema: {
    type: 'warning',
    icon: 'fa-solid fa-rotate',
    title: 'Restaurar Sistema',
    message: 'Sistema restaurado correctamente',
    duration: 6000,
  },
  actualizacionSistema: {
    type: 'info',
    icon: 'fa-solid fa-cloud-arrow-down',
    title: 'Actualización',
    message: 'Nueva actualización disponible',
    duration: 6000,
  },
  sistemaActualizado: {
    type: 'success',
    icon: 'fa-solid fa-check-double',
    title: 'Sistema Actualizado',
    message: 'Sistema actualizado correctamente',
    duration: 5000,
  },

  // Alertas de comunicación
  mensajeNuevo: {
    type: 'info',
    icon: 'fa-solid fa-envelope',
    title: 'Mensaje Nuevo',
    message: 'Ha recibido un nuevo mensaje',
    duration: 5000,
  },
  mensajeEnviado: {
    type: 'success',
    icon: 'fa-solid fa-paper-plane',
    title: 'Mensaje Enviado',
    message: 'Mensaje enviado correctamente',
    duration: 4000,
  },
  notificacionPush: {
    type: 'info',
    icon: 'fa-solid fa-bell',
    title: 'Notificación',
    message: 'Nueva notificación recibida',
    duration: 4000,
  },

  // Alertas de reportes y estadísticas
  reporteGenerado: {
    type: 'success',
    icon: 'fa-solid fa-chart-column',
    title: 'Reporte Generado',
    message: 'El reporte ha sido generado exitosamente',
    duration: 5000,
  },
  exportarEstadisticas: {
    type: 'success',
    icon: 'fa-solid fa-file-csv',
    title: 'Exportar Estadísticas',
    message: 'Estadísticas exportadas correctamente',
    duration: 5000,
  },
  graficosActualizados: {
    type: 'info',
    icon: 'fa-solid fa-chart-pie',
    title: 'Gráficos Actualizados',
    message: 'Los gráficos se han actualizado',
    duration: 4000,
  },

  // Alertas de seguros médicos
  seguroRechazado: {
    type: 'error',
    icon: 'fa-solid fa-rectangle-xmark',
    title: 'Seguro Rechazado',
    message: 'El seguro médico ha sido rechazado',
    duration: 6000,
  },
  autorizacionSeguro: {
    type: 'info',
    icon: 'fa-solid fa-clipboard-list',
    title: 'Autorización de Seguro',
    message: 'Solicitando autorización',
    duration: 5000,
  },
  reclamoEnviado: {
    type: 'success',
    icon: 'fa-solid fa-file-contract',
    title: 'Reclamo Enviado',
    message: 'Reclamo enviado al seguro',
    duration: 5000,
  },

  // Alertas de métodos de pago
  plin: {
    type: 'plin',
    icon: 'fa-solid fa-wallet',
    title: 'Plin',
    message: 'Transferencia realizada con éxito',
    duration: 5000,
  },
  yape: {
    type: 'yape',
    icon: 'fa-solid fa-money-bill-transfer',
    title: 'Yape',
    message: 'Método de pago Yape',
    duration: 5000,
  },
  efectivo: {
    type: 'info',
    icon: 'fa-solid fa-money-bill-wave',
    title: 'Actualizado',
    message: 'Método de pago Efectivo',
    duration: 5000,
  },
  pagoelminado: {
    type: 'success',
    icon: 'fa-solid fa-trash-can',
    title: 'Eliminado',
    message: 'Pago eliminado exitosamente',
    duration: 5000,
  },

  actualizadouser: {
    type: 'info',
    icon: 'fa-solid fa-user-pen',
    title: 'Actualizado',
    message: 'Aquí hay información importante',
    duration: 5000,
  },

  imageUploadSuccess: {
    type: 'info',
    icon: 'fa-solid fa-image',
    title: 'Imagen subida',
    message: 'Tu imagen se ha actualizado correctamente',
    duration: 5000,
  },
};
